Lgan#4676 | discord.py | raise 
Ignoring exception in command raise:
Traceback (most recent call last):
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 891, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Logan\Documents\Python\Discord\Pets\cogs\dev.py", line 33, in raise_
    raise commands.CommandError("Raised")
discord.ext.commands.errors.CommandError: Raised

----Lgan#4676 | discord.py | raise 
Ignoring exception in command raise:
Traceback (most recent call last):
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 891, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Logan\Documents\Python\Discord\Pets\cogs\dev.py", line 33, in raise_
    raise commands.CommandError("Raised")
discord.ext.commands.errors.CommandError: Raised

----Lgan#4676 | discord.py | raise 
Ignoring exception in command raise:
Traceback (most recent call last):
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\bot.py", line 891, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Logan\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Logan\Documents\Python\Discord\Pets\cogs\dev.py", line 33, in raise_
    raise commands.CommandError("Raised")
discord.ext.commands.errors.CommandError: Raised

----